<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
            schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">
  <name>xarm_zed_handover</name>
  <version>0.0.0</version>
  <description>ROS2 package for xArm7 + ZED handover system</description>

  <maintainer email="jszdhyjs@gmail.com">huitao</maintainer>
  <license>Apache License 2.0</license>

  <!-- ======================   DEPENDENCIES       ====================== -->
  <!-- Python client library -->
  <exec_depend>rclpy</exec_depend>

  <!-- Messages used by ZED node -->
  <exec_depend>geometry_msgs</exec_depend>

  <!-- Service Trigger -->
  <exec_depend>std_srvs</exec_depend>

  <!-- Testing dependencies -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

